-- URL ARCHIVO COUNTRY: https://masterdatascience.s3.us-east-2.amazonaws.com/4.Inteligencia_negocio_visualizacion/WDICountry.csv
-- URL ARCHIVO DATA: https://masterdatascience.s3.us-east-2.amazonaws.com/4.Inteligencia_negocio_visualizacion/WDIData.csv
-- URL ARCHIVO SERIES: https://masterdatascience.s3.us-east-2.amazonaws.com/4.Inteligencia_negocio_visualizacion/WDISeries.csv